Homework 1st.
qlcid/spring-boot-study pull request #3
Opened 2020-07-21 07:57 UTC by qlcid

- order API

2020-07-21 09:41 UTC, donggov requested changes

2020-07-21 09:41 UTC, donggov commented on src/main/java/com/study/yeseul/order/service/OrderService.java
> +                .orElseThrow(() -> new IllegalArgumentException("해당 상품이 없습니다. id=" + id));
데이터가 없을 경우에는 HTTP 코드를 500보다는 404로 반환하는게 좋습니다.
어떻게하면 HTTP 코드를 404로 반환할 수 있을까요? ^^

2020-07-21 09:41 UTC, donggov commented on src/main/java/com/study/yeseul/order/controller/OrderController.java
> +    @PostMapping("/{productId}")
productId를 Path로 받아도 문제는 없지만
body로 받는게 설계상 더 좋습니다~.
잘하셨어요. 👍

2020-07-21 09:41 UTC, donggov commented on src/main/java/com/study/yeseul/order/vo/OrderDto.java
> +    @Setter
@Setter가 꼭 필요없는 곳들은 다 제거해주세요.
유지해도 상관이 없지만, 제거하게되면 개발자가 실수로 값을 바꾸게 되는 실수를 방지할 수 있습니다.

2020-07-23 17:16 UTC, qlcid commented on src/main/java/com/study/yeseul/order/service/OrderService.java
> +                .orElseThrow(() -> new IllegalArgumentException("해당 상품이 없습니다. id=" + id));
404를 반환하도록 에러를 처리해주는 custom exception 클래스를 만드는 방식으로 하면 될까요..?

2020-07-24 04:56 UTC, donggov commented on src/main/java/com/study/yeseul/order/service/OrderService.java
> +                .orElseThrow(() -> new IllegalArgumentException("해당 상품이 없습니다. id=" + id));
> 404를 반환하도록 에러를 처리해주는 custom exception 클래스를 만드는 방식으로 하면 될까요..?

빙고. 다음 멘토링 시간에 같이 해봅시다.

2020-07-27 04:52 UTC, merged